apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: "*"
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"ecopaths:staging","namespace":"ohtuprojekti-staging"},"fieldPath":"spec.template.spec.containers[?(@.name==\"ecopaths\")].image","pause":"false"}]
  name: ecopaths-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecopaths
  template:
    metadata:
      labels:
        app: ecopaths
    spec:
      containers:
        - name: ecopaths
          image: ecopaths:staging
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: ecopaths-config
                  key: DB_URL
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ecopaths-google-api
                  key: GOOGLE_API_KEY
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ecopaths-upstash-redis
                  key: REDIS_URL
            - name: REACT_APP_API_URL
              valueFrom:
                secretKeyRef:
                  name: ecopaths-app-api-url
                  key: REACT_APP_API_URL
            - name: REACT_APP_MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: ecopaths-mapbox-token
                  key: REACT_APP_MAPBOX_TOKEN
            - name: REACT_APP_MAPBOX_STYLE
              valueFrom:
                secretKeyRef:
                  name: ecopaths-mapbox-style
                  key: REACT_APP_MAPBOX_STYLE
            - name: GEOAPIFY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ecopaths-geoapify-key
                  key: GEOAPIFY_API_KEY
          resources:
            limits:
              memory: "750Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "100m"
